#!/usr/bin/env bash
set -euo pipefail

WINDOWS_HOST="${AEGIS_WINDOWS_HOST:-192.168.12.101}"
WINDOWS_USER="${AEGIS_WINDOWS_USER:-aegis}"
SSH_KEY="${AEGIS_WINDOWS_SSH_KEY:-$HOME/.ssh/id_ed25519}"
REMOTE_PORT="${AEGIS_TUNNEL_REMOTE_PORT:-9091}"
LOCAL_HOST="${AEGIS_TUNNEL_LOCAL_HOST:-127.0.0.1}"
LOCAL_PORT="${AEGIS_TUNNEL_LOCAL_PORT:-9091}"
ACTIONS_REMOTE_PORT="${AEGIS_ACTIONS_TUNNEL_REMOTE_PORT:-8083}"
ACTIONS_LOCAL_PORT="${AEGIS_ACTIONS_TUNNEL_LOCAL_PORT:-8083}"
DETECTION_REMOTE_PORT="${AEGIS_DETECTION_TUNNEL_REMOTE_PORT:-8089}"
DETECTION_LOCAL_PORT="${AEGIS_DETECTION_TUNNEL_LOCAL_PORT:-8089}"

exec /usr/bin/ssh \
  -i "$SSH_KEY" \
  -N \
  -T \
  -o StrictHostKeyChecking=accept-new \
  -o UserKnownHostsFile=/private/tmp/aegisflux_known_hosts \
  -o ExitOnForwardFailure=yes \
  -o ServerAliveInterval=30 \
  -o ServerAliveCountMax=3 \
  -R "${REMOTE_PORT}:${LOCAL_HOST}:${LOCAL_PORT}" \
  -R "${ACTIONS_REMOTE_PORT}:${LOCAL_HOST}:${ACTIONS_LOCAL_PORT}" \
  -R "${DETECTION_REMOTE_PORT}:${LOCAL_HOST}:${DETECTION_LOCAL_PORT}" \
  "${WINDOWS_USER}@${WINDOWS_HOST}"
