import type { CSSProperties } from 'react'

export const shellStyles: Record<string, CSSProperties> = {
  page: {
    minHeight: '100vh',
    background: '#f8fafc',
    color: '#0f172a',
    fontFamily: 'Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  header: {
    background: '#fff',
    borderBottom: '1px solid #e5e7eb',
    boxShadow: '0 1px 2px rgba(15, 23, 42, 0.05)',
  },
  headerInner: {
    height: 64,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 16px',
    gap: 16,
  },
  headerLogo: { display: 'flex', alignItems: 'center', gap: 12, minWidth: 230 },
  headerLogoMark: {
    width: 38,
    height: 38,
    borderRadius: 9,
    background: '#020617',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  logoImage: { width: '100%', height: '100%', objectFit: 'cover', display: 'block' },
  wordmarkText: {
    margin: 0,
    fontSize: 21,
    lineHeight: '23px',
    fontWeight: 850,
    letterSpacing: 0.4,
    color: '#0f172a',
  },
  wordmarkFlux: {
    color: '#2563eb',
  },
  headerActions: { display: 'flex', alignItems: 'center', gap: 12 },
  headerSearch: {
    height: 34,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    border: 0,
    borderRadius: 8,
    background: '#f1f5f9',
    color: '#64748b',
    padding: '0 10px',
    fontSize: 14,
  },
  keycap: {
    border: '1px solid #cbd5e1',
    borderRadius: 5,
    background: '#fff',
    color: '#94a3b8',
    padding: '1px 5px',
    fontSize: 11,
    fontWeight: 700,
  },
  iconButton: {
    width: 36,
    height: 36,
    border: 0,
    borderRadius: 8,
    background: 'transparent',
    color: '#64748b',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  headerStatus: { display: 'inline-flex', alignItems: 'center', gap: 8, paddingLeft: 12, borderLeft: '1px solid #e5e7eb' },
  userBadge: { display: 'inline-flex', alignItems: 'center', gap: 8, paddingLeft: 12, borderLeft: '1px solid #e5e7eb' },
  rolePill: { border: '1px solid #bfdbfe', background: '#eff6ff', color: '#1d4ed8', borderRadius: 5, padding: '2px 6px', fontSize: 11, fontWeight: 700 },
  aiHealthChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    marginLeft: 8,
    padding: '4px 10px',
    borderRadius: 999,
    border: '1px solid #e2e8f0',
    background: '#f8fafc',
    fontSize: 12,
    fontWeight: 650,
    color: '#475569',
  },
  appShell: { display: 'flex', height: '100vh', flexDirection: 'column', overflow: 'hidden' },
  bodyShell: { display: 'flex', minHeight: 0, flex: 1, overflow: 'hidden' },
  sidebar: {
    width: 264,
    flexShrink: 0,
    background: '#fff',
    borderRight: '1px solid #e5e7eb',
    display: 'flex',
    flexDirection: 'column',
    overflowY: 'auto',
  },
  sideNav: { padding: 16, display: 'grid', gap: 4 },
  sideGroupLabel: {
    padding: '20px 12px 6px',
    fontSize: 11,
    fontWeight: 800,
    color: '#94a3b8',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  sideButton: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    border: 0,
    borderRadius: 8,
    background: 'transparent',
    color: '#475569',
    padding: '10px 12px',
    fontSize: 14,
    fontWeight: 600,
    textAlign: 'left',
    cursor: 'pointer',
  },
  sideButtonActive: { background: '#2563eb', color: '#fff' },
  sideButtonMuted: { color: '#475569', cursor: 'default' },
  sideFooter: { marginTop: 'auto', padding: 14, borderTop: '1px solid #e5e7eb' },
  sideFooterCard: { borderRadius: 10, border: '1px solid #bae6fd', background: '#f0f9ff', padding: 12 },
  contentArea: { minWidth: 0, flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  scrollArea: { flex: 1, minHeight: 0, overflow: 'auto' },
  breadcrumb: {
    height: 38,
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '0 20px',
    borderBottom: '1px solid #f1f5f9',
    background: '#fff',
    color: '#64748b',
    fontSize: 13,
    flexShrink: 0,
  },
}
